### ISSUE TITLE
Ledger tutorial: port and update

### ISSUE THREAD

**Issue by svub** [nimiq/nimiq.github.io#10]
The [original tutorial on how to use the Ledger](https://www.nimiq.com/tutorials/ledger/) is a bit dated and not aligned with all other tutorials.

So it would be great to:
* Create an MD file in `/tutorials/` and port the content from the URL (check out `/tutorials/nimiq-checkout.md` for inspiration)
* Update the content: update texts, but especially screenshots (they'll go into `/tutorials/resources`)
* Add a link to the tutorial over page at `/pages/tutorials.md`

**Comment by mariofriz** [comment]
I'd be willing to do this.

How about adding it to https://www.nimiq.com/developers/ though, it looks cleaner and more in line with the Nimiq style.

**Comment by svub** [comment]
Hi @mariofriz! Yes you're right, the thing is, the dev center is still work-in-progress, the goal later is to integrate all tutorials there. :)

For now, the idea is to link it in the dev center once it's ported - like all the other tutorials, have them in one place, so it's easy for devs to find them.
